import React from "react";

const Select = props => {
  return (
    <form onSubmit={props.fetchDogs}>
      <select onChange={props.handleChange}>
        <option value="random">random</option>
        <option value="affenpinscher">affenpinscher</option>
        <option value="hound/afghan">afghan hound</option>
        <option value="african">african</option>
        <option value="airedale">airedale terrier</option>
        <option value="akita">akita</option>
        <option value="terrier/american">american terrier</option>
        <option value="appenzeller">appenzeller</option>
        <option value="cattledog/australian">australian cattledog</option>
        <option value="terrier/australian">australian terrier</option>
        <option value="basenji">basenji</option>
        <option value="hound/basset">basset hound</option>
        <option value="beagle">beagle</option>
        <option value="terrier/bedlington">bedlington terrier</option>
        <option value="mountain/bernese">bernese mountain dog</option>
        <option value="frise/bichon">bichon frise</option>
        <option value="spaniel/blenheim">blenheim spaniel</option>
        <option value="hound/blood">blood hound</option>
        <option value="bluetick">bluetick</option>
        <option value="collie/border">border collie</option>
        <option value="terrier/border">border terrier</option>
        <option value="borzoi">borzoi</option>
        <option value="bulldog/boston">boston bulldog</option>
        <option value="bouvier">bouvier</option>
        <option value="boxer">boxer</option>
        <option value="brabancon">brabancon</option>
        <option value="briard">briard</option>
        <option value="spaniel/brittany">brittany spaniel</option>
        <option value="mastiff/bull">bull mastiff</option>
        <option value="cairn">cairn</option>
        <option value="corgi">cardigan welsh corgi</option>
        <option value="retriever/chesapeake">chesapeake bay retriever</option>
        <option value="chihuahua">chihuahua</option>
        <option value="chow">chow chow</option>
        <option value="clumber">clumber spaniel</option>
        <option value="cockapoo">cockapoo</option>
        <option value="spaniel/cocker">cocker spaniel</option>
        <option value="coonhound">coonhound</option>
        <option value="cotondetulear">cotondetulear</option>
        <option value="retriever/curly">curly-coated retriever</option>
        <option value="dachshund">dachshund</option>
        <option value="dalmatian">dalmatian</option>
        <option value="terrier/dandie">dandie terrier</option>
        <option value="dhole">dhole</option>
        <option value="dingo">dingo</option>
        <option value="doberman">doberman pinscher</option>
        <option value="bulldog/english">english bulldog</option>
        <option value="hound/english">english hound</option>
        <option value="mastiff/english">english mastiff</option>
        <option value="setter/english">english setter</option>
        <option value="sheepdog/english">english sheepdog</option>
        <option value="entlebucher">entlebucher</option>
        <option value="eskimo">eskimo</option>
        <option value="retriever/flatcoated">flat-coated retriever</option>
        <option value="terrier/fox">fox terrier</option>
        <option value="bulldog/french">french bulldog</option>
        <option value="pointer/germanlonghair">german longhair pointer</option>
        <option value="pointer/german">german pointer</option>
        <option value="germanshepherd">german shepherd</option>
        <option value="schnauzer/giant">giant schnauzer</option>
        <option value="retriever/golden">golden retriever</option>
        <option value="setter/gordon">gordon setter</option>
        <option value="dane/great">great dane</option>
        <option value="pyrenees">great pyrenees</option>
        <option value="groenendael">groenendael</option>
        <option value="husky">husky</option>
        <option value="hound/ibizan">ibizan hound</option>
        <option value="setter/irish">irish setter</option>
        <option value="spaniel/irish">irish spaniel</option>
        <option value="terrier/irish">irish terrier</option>
        <option value="wolfhound-irish">irish wolfhound</option>
        <option value="greyhound/italian">italian greyhound</option>
        <option value="terrier/russell">jack russell terrier</option>
        <option value="spaniel/japanese">japanese spaniel</option>
        <option value="keeshond">keeshond</option>
        <option value="kelpie">kelpie</option>
        <option value="terrier/kerryblue">kerry blue terrier</option>
        <option value="komondor">komondor</option>
        <option value="kuvasz">kuvasz</option>
        <option value="labrador">labrador retriever</option>
        <option value="terrier/lakeland">lakeland terrier</option>
        <option value="leonberg">leonberg</option>
        <option value="lhasa">lhasa apso</option>
        <option value="malamute">malamute</option>
        <option value="malinois">malinois</option>
        <option value="maltese">maltese</option>
        <option value="mexicanhairless">mexican hairless</option>
        <option value="pinscher/miniature">miniature pinscher</option>
        <option value="poodle/miniature">miniature poodle</option>
        <option value="schnauzer/miniature">miniature schnauzer</option>
        <option value="mix">mix</option>
        <option value="newfoundland">newfoundland</option>
        <option value="terrier/norfolk">norfolk terrier</option>
        <option value="buhund/norwegian">norwegian buhund</option>
        <option value="elkhound/norwegian">norwegian elkhound</option>
        <option value="terrier/norwich">norwich terrier</option>
        <option value="otterhound">otterhound</option>
        <option value="papillon">papillon</option>
        <option value="terrier/patterdale">patterdale terrier</option>
        <option value="pekinese">pekinese</option>
        <option value="pembroke">pembroke welsh corgi</option>
        <option value="pomeranian">pomeranian</option>
        <option value="pug">pug</option>
        <option value="puggle">puggle</option>
        <option value="redbone">redbone</option>
        <option value="ridgeback/rhodesian">rhodesian ridgeback</option>
        <option value="rottweiler">rottweiler</option>
        <option value="saluki">saluki</option>
        <option value="samoyed">samoyed</option>
        <option value="schipperke">schipperke</option>
        <option value="deerhound/scottish">scottish deerhound</option>
        <option value="terrier/scottish">scottish terrier</option>
        <option value="terrier/sealyham">sealyham terrier</option>
        <option value="sheepdog/shetland">shetland sheepdog</option>
        <option value="shiba">shiba inu</option>
        <option value="shihtzu">shihtzu</option>
        <option value="terrier/silky">silky terrier</option>
        <option value="waterdog-spanish">spanish waterdog</option>
        <option value="springer/english">springer spaniel</option>
        <option value="stbernard">st. bernard</option>
        <option value="bullterrier/staffordshire">staffordshire bullterrier</option>
        <option value="poodle/standard">standard poodle</option>
        <option value="spaniel/sussex">sussex spaniel</option>
        <option value="mountain/swiss">swiss mountain dog</option>
        <option value="mastiff/tibetan">tibetan mastiff</option>
        <option value="terrier/tibetan">tibetan terrier</option>
        <option value="poodle/toy">toy poodle</option>
        <option value="terrier/toy">toy terrier</option>
        <option value="vizsla">vizsla</option>
        <option value="hound/walker">walker hound</option>
        <option value="weimaraner">weimaraner</option>
        <option value="spaniel/welsh">welsh spaniel</option>
        <option value="terrier/westhighland">west highland terrier</option>
        <option value="terrier/wheaten">wheaten terrier</option>
        <option value="whippet">whippet</option>
        <option value="terrier/yorkshire">yorkshire terrier</option>
      </select>
      <button type="submit">Fetch Dogs!</button>
    </form>
  );
};

export default Select;
